// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuditEventsByTenant = `-- name: GetAuditEventsByTenant :many
SELECT id, actor_email, action, entity_type, entity_id, details, ip_address, created_at 
FROM audit_events
WHERE tenant_id = $1 AND org_id = $2
ORDER BY created_at DESC
LIMIT 50
`

type GetAuditEventsByTenantParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

type GetAuditEventsByTenantRow struct {
	ID         pgtype.UUID        `json:"id"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    []byte             `json:"details"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAuditEventsByTenant(ctx context.Context, arg GetAuditEventsByTenantParams) ([]GetAuditEventsByTenantRow, error) {
	rows, err := q.db.Query(ctx, getAuditEventsByTenant, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAuditEventsByTenantRow
	for rows.Next() {
		var i GetAuditEventsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_events (
    org_id,
    tenant_id,
    actor_email,
    action,
    entity_type,
    entity_id,
    details,
    ip_address
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type InsertAuditEventParams struct {
	OrgID      pgtype.UUID `json:"org_id"`
	TenantID   pgtype.UUID `json:"tenant_id"`
	ActorEmail pgtype.Text `json:"actor_email"`
	Action     string      `json:"action"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Details    []byte      `json:"details"`
	IpAddress  pgtype.Text `json:"ip_address"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.OrgID,
		arg.TenantID,
		arg.ActorEmail,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Details,
		arg.IpAddress,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
