// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrUpdateProductChannelListing = `-- name: CreateOrUpdateProductChannelListing :one
INSERT INTO product_channel_listings (
    product_id, channel_id, org_id, tenant_id, is_published, published_at, override_title, override_description, channel_price
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (product_id, channel_id) DO UPDATE SET
    is_published = EXCLUDED.is_published,
    published_at = EXCLUDED.published_at,
    override_title = EXCLUDED.override_title,
    override_description = EXCLUDED.override_description,
    channel_price = EXCLUDED.channel_price,
    updated_at = CURRENT_TIMESTAMP
RETURNING product_id, channel_id, org_id, tenant_id, is_published, published_at, override_title, override_description, channel_price, created_at, updated_at
`

type CreateOrUpdateProductChannelListingParams struct {
	ProductID           pgtype.UUID        `json:"product_id"`
	ChannelID           pgtype.UUID        `json:"channel_id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	IsPublished         pgtype.Bool        `json:"is_published"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	OverrideTitle       pgtype.Text        `json:"override_title"`
	OverrideDescription pgtype.Text        `json:"override_description"`
	ChannelPrice        pgtype.Numeric     `json:"channel_price"`
}

func (q *Queries) CreateOrUpdateProductChannelListing(ctx context.Context, arg CreateOrUpdateProductChannelListingParams) (ProductChannelListing, error) {
	row := q.db.QueryRow(ctx, createOrUpdateProductChannelListing,
		arg.ProductID,
		arg.ChannelID,
		arg.OrgID,
		arg.TenantID,
		arg.IsPublished,
		arg.PublishedAt,
		arg.OverrideTitle,
		arg.OverrideDescription,
		arg.ChannelPrice,
	)
	var i ProductChannelListing
	err := row.Scan(
		&i.ProductID,
		&i.ChannelID,
		&i.OrgID,
		&i.TenantID,
		&i.IsPublished,
		&i.PublishedAt,
		&i.OverrideTitle,
		&i.OverrideDescription,
		&i.ChannelPrice,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSalesChannel = `-- name: CreateSalesChannel :one
INSERT INTO sales_channels (
    org_id, tenant_id, name, currency, is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, org_id, tenant_id, name, currency, is_active, created_at, updated_at
`

type CreateSalesChannelParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Currency pgtype.Text `json:"currency"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) CreateSalesChannel(ctx context.Context, arg CreateSalesChannelParams) (SalesChannel, error) {
	row := q.db.QueryRow(ctx, createSalesChannel,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.Currency,
		arg.IsActive,
	)
	var i SalesChannel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.Currency,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductWithChannelOverrides = `-- name: GetProductWithChannelOverrides :one
SELECT 
    p.id as product_id,
    COALESCE(pcl.override_title, p.title)::varchar as title,
    COALESCE(pcl.override_description, p.description)::text as description,
    COALESCE(pcl.channel_price, pv.price)::numeric as price,
    pcl.is_published,
    pcl.published_at
FROM products p
LEFT JOIN product_variants pv ON p.id = pv.product_id -- Simplification: grabbing first variant price
LEFT JOIN product_channel_listings pcl ON p.id = pcl.product_id AND pcl.channel_id = $2
WHERE p.id = $1 AND p.tenant_id = $3 AND p.org_id = $4
LIMIT 1
`

type GetProductWithChannelOverridesParams struct {
	ID        pgtype.UUID `json:"id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	OrgID     pgtype.UUID `json:"org_id"`
}

type GetProductWithChannelOverridesRow struct {
	ProductID   pgtype.UUID        `json:"product_id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	IsPublished pgtype.Bool        `json:"is_published"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
}

func (q *Queries) GetProductWithChannelOverrides(ctx context.Context, arg GetProductWithChannelOverridesParams) (GetProductWithChannelOverridesRow, error) {
	row := q.db.QueryRow(ctx, getProductWithChannelOverrides,
		arg.ID,
		arg.ChannelID,
		arg.TenantID,
		arg.OrgID,
	)
	var i GetProductWithChannelOverridesRow
	err := row.Scan(
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.IsPublished,
		&i.PublishedAt,
	)
	return i, err
}

const listSalesChannels = `-- name: ListSalesChannels :many
SELECT id, org_id, tenant_id, name, currency, is_active, created_at, updated_at FROM sales_channels
WHERE tenant_id = $1 AND org_id = $2
ORDER BY created_at DESC
`

type ListSalesChannelsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) ListSalesChannels(ctx context.Context, arg ListSalesChannelsParams) ([]SalesChannel, error) {
	rows, err := q.db.Query(ctx, listSalesChannels, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SalesChannel
	for rows.Next() {
		var i SalesChannel
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Name,
			&i.Currency,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
