// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: integrations.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantIntegration = `-- name: CreateTenantIntegration :one
INSERT INTO tenant_integrations (
    tenant_id, org_id, connection_id, category
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, org_id, tenant_id, connection_id, category, created_at
`

type CreateTenantIntegrationParams struct {
	TenantID     pgtype.UUID         `json:"tenant_id"`
	OrgID        pgtype.UUID         `json:"org_id"`
	ConnectionID string              `json:"connection_id"`
	Category     IntegrationCategory `json:"category"`
}

func (q *Queries) CreateTenantIntegration(ctx context.Context, arg CreateTenantIntegrationParams) (TenantIntegration, error) {
	row := q.db.QueryRow(ctx, createTenantIntegration,
		arg.TenantID,
		arg.OrgID,
		arg.ConnectionID,
		arg.Category,
	)
	var i TenantIntegration
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ConnectionID,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantIntegrationByCategory = `-- name: GetTenantIntegrationByCategory :one
SELECT connection_id FROM tenant_integrations WHERE tenant_id = $1 AND category = $2 LIMIT 1
`

type GetTenantIntegrationByCategoryParams struct {
	TenantID pgtype.UUID         `json:"tenant_id"`
	Category IntegrationCategory `json:"category"`
}

func (q *Queries) GetTenantIntegrationByCategory(ctx context.Context, arg GetTenantIntegrationByCategoryParams) (string, error) {
	row := q.db.QueryRow(ctx, getTenantIntegrationByCategory, arg.TenantID, arg.Category)
	var connection_id string
	err := row.Scan(&connection_id)
	return connection_id, err
}
