// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type FulfillmentStatus string

const (
	FulfillmentStatusPending        FulfillmentStatus = "pending"
	FulfillmentStatusAssigned       FulfillmentStatus = "assigned"
	FulfillmentStatusPicked         FulfillmentStatus = "picked"
	FulfillmentStatusPacked         FulfillmentStatus = "packed"
	FulfillmentStatusShipped        FulfillmentStatus = "shipped"
	FulfillmentStatusOutForDelivery FulfillmentStatus = "out_for_delivery"
	FulfillmentStatusDelivered      FulfillmentStatus = "delivered"
	FulfillmentStatusCancelled      FulfillmentStatus = "cancelled"
	FulfillmentStatusFailed         FulfillmentStatus = "failed"
)

func (e *FulfillmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FulfillmentStatus(s)
	case string:
		*e = FulfillmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FulfillmentStatus: %T", src)
	}
	return nil
}

type NullFulfillmentStatus struct {
	FulfillmentStatus FulfillmentStatus `json:"fulfillment_status"`
	Valid             bool              `json:"valid"` // Valid is true if FulfillmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFulfillmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FulfillmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FulfillmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFulfillmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FulfillmentStatus), nil
}

type IntegrationCategory string

const (
	IntegrationCategoryCommerce   IntegrationCategory = "commerce"
	IntegrationCategoryCrm        IntegrationCategory = "crm"
	IntegrationCategoryTicketing  IntegrationCategory = "ticketing"
	IntegrationCategoryAts        IntegrationCategory = "ats"
	IntegrationCategoryAccounting IntegrationCategory = "accounting"
)

func (e *IntegrationCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IntegrationCategory(s)
	case string:
		*e = IntegrationCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for IntegrationCategory: %T", src)
	}
	return nil
}

type NullIntegrationCategory struct {
	IntegrationCategory IntegrationCategory `json:"integration_category"`
	Valid               bool                `json:"valid"` // Valid is true if IntegrationCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIntegrationCategory) Scan(value interface{}) error {
	if value == nil {
		ns.IntegrationCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IntegrationCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIntegrationCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IntegrationCategory), nil
}

type OrderStatus string

const (
	OrderStatusDraft              OrderStatus = "draft"
	OrderStatusPendingPayment     OrderStatus = "pending_payment"
	OrderStatusPaymentAuthorized  OrderStatus = "payment_authorized"
	OrderStatusConfirmed          OrderStatus = "confirmed"
	OrderStatusProcessing         OrderStatus = "processing"
	OrderStatusPartiallyFulfilled OrderStatus = "partially_fulfilled"
	OrderStatusFulfilled          OrderStatus = "fulfilled"
	OrderStatusDelivered          OrderStatus = "delivered"
	OrderStatusCompleted          OrderStatus = "completed"
	OrderStatusCancelled          OrderStatus = "cancelled"
	OrderStatusReturnRequested    OrderStatus = "return_requested"
	OrderStatusPartiallyReturned  OrderStatus = "partially_returned"
	OrderStatusReturned           OrderStatus = "returned"
	OrderStatusRefunded           OrderStatus = "refunded"
	OrderStatusPartiallyRefunded  OrderStatus = "partially_refunded"
	OrderStatusFailed             OrderStatus = "failed"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PoStatus string

const (
	PoStatusDRAFT           PoStatus = "DRAFT"
	PoStatusPENDINGAPPROVAL PoStatus = "PENDING_APPROVAL"
	PoStatusAPPROVED        PoStatus = "APPROVED"
	PoStatusSENT            PoStatus = "SENT"
	PoStatusRECEIVED        PoStatus = "RECEIVED"
	PoStatusCANCELLED       PoStatus = "CANCELLED"
)

func (e *PoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PoStatus(s)
	case string:
		*e = PoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PoStatus: %T", src)
	}
	return nil
}

type NullPoStatus struct {
	PoStatus PoStatus `json:"po_status"`
	Valid    bool     `json:"valid"` // Valid is true if PoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PoStatus), nil
}

type RefundReason string

const (
	RefundReasonCustomerRequest RefundReason = "customer_request"
	RefundReasonOrderCancelled  RefundReason = "order_cancelled"
	RefundReasonReturnReceived  RefundReason = "return_received"
	RefundReasonDuplicateCharge RefundReason = "duplicate_charge"
	RefundReasonFraud           RefundReason = "fraud"
	RefundReasonOther           RefundReason = "other"
)

func (e *RefundReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundReason(s)
	case string:
		*e = RefundReason(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundReason: %T", src)
	}
	return nil
}

type NullRefundReason struct {
	RefundReason RefundReason `json:"refund_reason"`
	Valid        bool         `json:"valid"` // Valid is true if RefundReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundReason) Scan(value interface{}) error {
	if value == nil {
		ns.RefundReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundReason), nil
}

type RefundStatus string

const (
	RefundStatusPending    RefundStatus = "pending"
	RefundStatusProcessing RefundStatus = "processing"
	RefundStatusSucceeded  RefundStatus = "succeeded"
	RefundStatusFailed     RefundStatus = "failed"
	RefundStatusCancelled  RefundStatus = "cancelled"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus `json:"refund_status"`
	Valid        bool         `json:"valid"` // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type ReturnItemDisposition string

const (
	ReturnItemDispositionPending   ReturnItemDisposition = "pending"
	ReturnItemDispositionSellable  ReturnItemDisposition = "sellable"
	ReturnItemDispositionDamaged   ReturnItemDisposition = "damaged"
	ReturnItemDispositionRefurbish ReturnItemDisposition = "refurbish"
	ReturnItemDispositionLiquidate ReturnItemDisposition = "liquidate"
	ReturnItemDispositionScrap     ReturnItemDisposition = "scrap"
)

func (e *ReturnItemDisposition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReturnItemDisposition(s)
	case string:
		*e = ReturnItemDisposition(s)
	default:
		return fmt.Errorf("unsupported scan type for ReturnItemDisposition: %T", src)
	}
	return nil
}

type NullReturnItemDisposition struct {
	ReturnItemDisposition ReturnItemDisposition `json:"return_item_disposition"`
	Valid                 bool                  `json:"valid"` // Valid is true if ReturnItemDisposition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReturnItemDisposition) Scan(value interface{}) error {
	if value == nil {
		ns.ReturnItemDisposition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReturnItemDisposition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReturnItemDisposition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReturnItemDisposition), nil
}

type ReturnStatus string

const (
	ReturnStatusRequested  ReturnStatus = "requested"
	ReturnStatusAuthorized ReturnStatus = "authorized"
	ReturnStatusInTransit  ReturnStatus = "in_transit"
	ReturnStatusReceived   ReturnStatus = "received"
	ReturnStatusInspected  ReturnStatus = "inspected"
	ReturnStatusRestocked  ReturnStatus = "restocked"
	ReturnStatusRejected   ReturnStatus = "rejected"
	ReturnStatusCompleted  ReturnStatus = "completed"
	ReturnStatusCancelled  ReturnStatus = "cancelled"
)

func (e *ReturnStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReturnStatus(s)
	case string:
		*e = ReturnStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReturnStatus: %T", src)
	}
	return nil
}

type NullReturnStatus struct {
	ReturnStatus ReturnStatus `json:"return_status"`
	Valid        bool         `json:"valid"` // Valid is true if ReturnStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReturnStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReturnStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReturnStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReturnStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReturnStatus), nil
}

type Address struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	Line1       string             `json:"line1"`
	Line2       pgtype.Text        `json:"line2"`
	City        string             `json:"city"`
	State       pgtype.Text        `json:"state"`
	PostalCode  string             `json:"postal_code"`
	CountryCode string             `json:"country_code"`
	IsDefault   pgtype.Bool        `json:"is_default"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AiTask struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	TeamID           pgtype.UUID        `json:"team_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Title            string             `json:"title"`
	Status           string             `json:"status"`
	Priority         string             `json:"priority"`
	InputContext     []byte             `json:"input_context"`
	ProposedOutput   []byte             `json:"proposed_output"`
	RequiresApproval bool               `json:"requires_approval"`
	ApprovedBy       pgtype.UUID        `json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	DueAt            pgtype.Timestamptz `json:"due_at"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Attribute struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	Type      pgtype.Text        `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type AttributeGroup struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AttributeGroupLink struct {
	GroupID     pgtype.UUID `json:"group_id"`
	AttributeID pgtype.UUID `json:"attribute_id"`
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
}

type AttributeValue struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	AttributeID pgtype.UUID        `json:"attribute_id"`
	Value       string             `json:"value"`
	Slug        string             `json:"slug"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditEvent struct {
	ID         pgtype.UUID        `json:"id"`
	OrgID      pgtype.UUID        `json:"org_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorEmail pgtype.Text        `json:"actor_email"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Details    []byte             `json:"details"`
	IpAddress  pgtype.Text        `json:"ip_address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Brand struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type BulkJob struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	JobType        string             `json:"job_type"`
	Status         pgtype.Text        `json:"status"`
	PayloadJson    []byte             `json:"payload_json"`
	TotalItems     pgtype.Int4        `json:"total_items"`
	ProcessedItems pgtype.Int4        `json:"processed_items"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Category struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Name        string             `json:"name"`
	Slug        string             `json:"slug"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type CommerceConnection struct {
	ID                  pgtype.UUID        `json:"id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	UnifiedConnectionID string             `json:"unified_connection_id"`
	Provider            string             `json:"provider"`
	Status              pgtype.Text        `json:"status"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type CommerceItemMapping struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	ConnectionID  pgtype.UUID        `json:"connection_id"`
	ProductID     pgtype.UUID        `json:"product_id"`
	UnifiedItemID string             `json:"unified_item_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CommerceOrderMapping struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ConnectionID    pgtype.UUID        `json:"connection_id"`
	OrderID         pgtype.UUID        `json:"order_id"`
	UnifiedOrderID  string             `json:"unified_order_id"`
	ExternalOrderID string             `json:"external_order_id"`
	LastSyncedAt    pgtype.Timestamptz `json:"last_synced_at"`
	SyncDirection   string             `json:"sync_direction"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Customer struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	FirstName pgtype.Text        `json:"first_name"`
	LastName  pgtype.Text        `json:"last_name"`
	Phone     pgtype.Text        `json:"phone"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Fulfillment struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	LocationID        pgtype.UUID        `json:"location_id"`
	Status            FulfillmentStatus  `json:"status"`
	Carrier           pgtype.Text        `json:"carrier"`
	TrackingNumber    pgtype.Text        `json:"tracking_number"`
	TrackingUrl       pgtype.Text        `json:"tracking_url"`
	ShippedAt         pgtype.Timestamptz `json:"shipped_at"`
	DeliveredAt       pgtype.Timestamptz `json:"delivered_at"`
	EstimatedDelivery pgtype.Timestamptz `json:"estimated_delivery"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
}

type FulfillmentLineItem struct {
	ID              pgtype.UUID        `json:"id"`
	FulfillmentID   pgtype.UUID        `json:"fulfillment_id"`
	OrderLineItemID pgtype.UUID        `json:"order_line_item_id"`
	Quantity        int32              `json:"quantity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type HumanAiTeam struct {
	ID             pgtype.UUID        `json:"id"`
	OrgID          pgtype.UUID        `json:"org_id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	OwnerUserID    pgtype.UUID        `json:"owner_user_id"`
	Name           string             `json:"name"`
	Description    pgtype.Text        `json:"description"`
	Status         string             `json:"status"`
	CadenceMinutes int32              `json:"cadence_minutes"`
	ApprovalPolicy []byte             `json:"approval_policy"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type InventoryLedger struct {
	ID              pgtype.UUID        `json:"id"`
	OrgID           pgtype.UUID        `json:"org_id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	VariantID       pgtype.UUID        `json:"variant_id"`
	LocationID      pgtype.UUID        `json:"location_id"`
	TransactionType interface{}        `json:"transaction_type"`
	QuantityDelta   int32              `json:"quantity_delta"`
	ReferenceID     pgtype.Text        `json:"reference_id"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UnitCost        pgtype.Numeric     `json:"unit_cost"`
}

type InventoryLevel struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	VariantID         pgtype.UUID        `json:"variant_id"`
	LocationID        pgtype.UUID        `json:"location_id"`
	AvailableQuantity int32              `json:"available_quantity"`
	ReservedQuantity  int32              `json:"reserved_quantity"`
	UpdatedBy         pgtype.UUID        `json:"updated_by"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Location struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Type      pgtype.Text        `json:"type"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type OmsOutboxEvent struct {
	ID            pgtype.UUID        `json:"id"`
	Topic         string             `json:"topic"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	AggregateType string             `json:"aggregate_type"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	Payload       []byte             `json:"payload"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	FailedAt      pgtype.Timestamptz `json:"failed_at"`
	RetryCount    int32              `json:"retry_count"`
}

type Order struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	CustomerID        pgtype.UUID        `json:"customer_id"`
	ShippingAddressID pgtype.UUID        `json:"shipping_address_id"`
	BillingAddressID  pgtype.UUID        `json:"billing_address_id"`
	Status            OrderStatus        `json:"status"`
	Currency          string             `json:"currency"`
	Subtotal          pgtype.Numeric     `json:"subtotal"`
	DiscountTotal     pgtype.Numeric     `json:"discount_total"`
	ShippingTotal     pgtype.Numeric     `json:"shipping_total"`
	TaxTotal          pgtype.Numeric     `json:"tax_total"`
	Total             pgtype.Numeric     `json:"total"`
	PaymentStatus     pgtype.Text        `json:"payment_status"`
	PaymentProvider   pgtype.Text        `json:"payment_provider"`
	PaymentReference  pgtype.Text        `json:"payment_reference"`
	Channel           pgtype.Text        `json:"channel"`
	SourcePlatform    pgtype.Text        `json:"source_platform"`
	SalesChannelID    pgtype.UUID        `json:"sales_channel_id"`
	Notes             pgtype.Text        `json:"notes"`
	Tags              []string           `json:"tags"`
	Metadata          []byte             `json:"metadata"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
	CancelledAt       pgtype.Timestamptz `json:"cancelled_at"`
	FulfilledAt       pgtype.Timestamptz `json:"fulfilled_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type OrderEvent struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	EventType string             `json:"event_type"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	ActorRole pgtype.Text        `json:"actor_role"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type OrderLineItem struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             pgtype.UUID        `json:"org_id"`
	TenantID          pgtype.UUID        `json:"tenant_id"`
	OrderID           pgtype.UUID        `json:"order_id"`
	VariantID         pgtype.UUID        `json:"variant_id"`
	Sku               pgtype.Text        `json:"sku"`
	ProductTitle      string             `json:"product_title"`
	VariantTitle      pgtype.Text        `json:"variant_title"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	OptionValues      []byte             `json:"option_values"`
	Quantity          int32              `json:"quantity"`
	QuantityFulfilled int32              `json:"quantity_fulfilled"`
	QuantityReturned  int32              `json:"quantity_returned"`
	QuantityCancelled int32              `json:"quantity_cancelled"`
	DiscountTotal     pgtype.Numeric     `json:"discount_total"`
	TaxTotal          pgtype.Numeric     `json:"tax_total"`
	LineTotal         pgtype.Numeric     `json:"line_total"`
	RequiresShipping  pgtype.Bool        `json:"requires_shipping"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Product struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Status               pgtype.Text        `json:"status"`
	Options              []byte             `json:"options"`
	Metadata             []byte             `json:"metadata"`
	Embedding            pgvector.Vector    `json:"embedding"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	ProductTypeID        pgtype.UUID        `json:"product_type_id"`
	ShortDescription     pgtype.Text        `json:"short_description"`
	LongDescription      pgtype.Text        `json:"long_description"`
	Category             pgtype.Text        `json:"category"`
	Brand                pgtype.Text        `json:"brand"`
	Tags                 []byte             `json:"tags"`
	LaunchDate           pgtype.Timestamptz `json:"launch_date"`
	DiscontinueDate      pgtype.Timestamptz `json:"discontinue_date"`
	WarrantyPeriod       pgtype.Text        `json:"warranty_period"`
	IsTaxable            pgtype.Bool        `json:"is_taxable"`
	IsReturnable         pgtype.Bool        `json:"is_returnable"`
	RequiresSerialNumber pgtype.Bool        `json:"requires_serial_number"`
	SeoTitle             pgtype.Text        `json:"seo_title"`
	SeoDescription       pgtype.Text        `json:"seo_description"`
	SeoKeywords          []byte             `json:"seo_keywords"`
	DataQualityScore     pgtype.Int4        `json:"data_quality_score"`
	CategoryID           pgtype.UUID        `json:"category_id"`
	BrandID              pgtype.UUID        `json:"brand_id"`
}

type ProductChannelListing struct {
	ProductID           pgtype.UUID        `json:"product_id"`
	ChannelID           pgtype.UUID        `json:"channel_id"`
	OrgID               pgtype.UUID        `json:"org_id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	IsPublished         pgtype.Bool        `json:"is_published"`
	PublishedAt         pgtype.Timestamptz `json:"published_at"`
	OverrideTitle       pgtype.Text        `json:"override_title"`
	OverrideDescription pgtype.Text        `json:"override_description"`
	ChannelPrice        pgtype.Numeric     `json:"channel_price"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ProductMedium struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	VariantID pgtype.UUID        `json:"variant_id"`
	Url       string             `json:"url"`
	AltText   pgtype.Text        `json:"alt_text"`
	SortOrder pgtype.Int4        `json:"sort_order"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type ProductType struct {
	ID          pgtype.UUID        `json:"id"`
	OrgID       pgtype.UUID        `json:"org_id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProductTypeAttribute struct {
	ProductTypeID pgtype.UUID `json:"product_type_id"`
	AttributeID   pgtype.UUID `json:"attribute_id"`
	OrgID         pgtype.UUID `json:"org_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

type ProductVariant struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	ProductID        pgtype.UUID        `json:"product_id"`
	Sku              pgtype.Text        `json:"sku"`
	Barcode          pgtype.Text        `json:"barcode"`
	Price            pgtype.Numeric     `json:"price"`
	Currency         pgtype.Text        `json:"currency"`
	OptionValues     []byte             `json:"option_values"`
	Metadata         []byte             `json:"metadata"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	UpdatedBy        pgtype.UUID        `json:"updated_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CostPrice        pgtype.Numeric     `json:"cost_price"`
	DataQualityScore pgtype.Int4        `json:"data_quality_score"`
}

type PurchaseOrder struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	SupplierID           pgtype.UUID        `json:"supplier_id"`
	Status               NullPoStatus       `json:"status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Currency             pgtype.Text        `json:"currency"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ApprovedBy           pgtype.UUID        `json:"approved_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

type PurchaseOrderLineItem struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	PoID             pgtype.UUID        `json:"po_id"`
	VariantID        pgtype.UUID        `json:"variant_id"`
	Quantity         int32              `json:"quantity"`
	UnitPrice        pgtype.Numeric     `json:"unit_price"`
	Subtotal         pgtype.Numeric     `json:"subtotal"`
	ReceivedQuantity pgtype.Int4        `json:"received_quantity"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Refund struct {
	ID               pgtype.UUID        `json:"id"`
	OrgID            pgtype.UUID        `json:"org_id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	OrderID          pgtype.UUID        `json:"order_id"`
	ReturnID         pgtype.UUID        `json:"return_id"`
	Status           RefundStatus       `json:"status"`
	Reason           RefundReason       `json:"reason"`
	Amount           pgtype.Numeric     `json:"amount"`
	Currency         string             `json:"currency"`
	PaymentReference pgtype.Text        `json:"payment_reference"`
	Notes            pgtype.Text        `json:"notes"`
	ProcessedAt      pgtype.Timestamptz `json:"processed_at"`
	FailedReason     pgtype.Text        `json:"failed_reason"`
	Metadata         []byte             `json:"metadata"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Return struct {
	ID            pgtype.UUID        `json:"id"`
	OrgID         pgtype.UUID        `json:"org_id"`
	TenantID      pgtype.UUID        `json:"tenant_id"`
	OrderID       pgtype.UUID        `json:"order_id"`
	RmaNumber     pgtype.Text        `json:"rma_number"`
	Status        ReturnStatus       `json:"status"`
	Reason        pgtype.Text        `json:"reason"`
	Notes         pgtype.Text        `json:"notes"`
	RefundAmount  pgtype.Numeric     `json:"refund_amount"`
	RestockingFee pgtype.Numeric     `json:"restocking_fee"`
	ReceivedAt    pgtype.Timestamptz `json:"received_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ReturnLineItem struct {
	ID                pgtype.UUID               `json:"id"`
	ReturnID          pgtype.UUID               `json:"return_id"`
	OrderLineItemID   pgtype.UUID               `json:"order_line_item_id"`
	Quantity          int32                     `json:"quantity"`
	Reason            pgtype.Text               `json:"reason"`
	Disposition       NullReturnItemDisposition `json:"disposition"`
	RestockedQuantity pgtype.Int4               `json:"restocked_quantity"`
	CreatedAt         pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz        `json:"updated_at"`
}

type SalesChannel struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Currency  pgtype.Text        `json:"currency"`
	IsActive  pgtype.Bool        `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Supplier struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Name         string             `json:"name"`
	ContactEmail pgtype.Text        `json:"contact_email"`
	PaymentTerms pgtype.Text        `json:"payment_terms"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type SyncFailuresDlq struct {
	ID           pgtype.UUID        `json:"id"`
	OrgID        pgtype.UUID        `json:"org_id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ConnectionID pgtype.UUID        `json:"connection_id"`
	EntityType   string             `json:"entity_type"`
	EntityID     pgtype.UUID        `json:"entity_id"`
	Payload      []byte             `json:"payload"`
	ErrorMessage pgtype.Text        `json:"error_message"`
	RetryCount   pgtype.Int4        `json:"retry_count"`
	Status       pgtype.Text        `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	Name      string             `json:"name"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type TenantIntegration struct {
	ID           pgtype.UUID         `json:"id"`
	OrgID        pgtype.UUID         `json:"org_id"`
	TenantID     pgtype.UUID         `json:"tenant_id"`
	ConnectionID string              `json:"connection_id"`
	Category     IntegrationCategory `json:"category"`
	CreatedAt    pgtype.Timestamptz  `json:"created_at"`
}

type TenantSetting struct {
	ID                       pgtype.UUID        `json:"id"`
	OrgID                    pgtype.UUID        `json:"org_id"`
	TenantID                 pgtype.UUID        `json:"tenant_id"`
	InventoryAllocationModel pgtype.Text        `json:"inventory_allocation_model"`
	AutoPoEnabled            pgtype.Bool        `json:"auto_po_enabled"`
	DefaultLowStockThreshold pgtype.Int4        `json:"default_low_stock_threshold"`
	CostingMethod            pgtype.Text        `json:"costing_method"`
	UpdatedBy                pgtype.UUID        `json:"updated_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type ValidationIssue struct {
	ID        pgtype.UUID        `json:"id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	IssueType string             `json:"issue_type"`
	Severity  pgtype.Text        `json:"severity"`
	Message   string             `json:"message"`
	Resolved  pgtype.Bool        `json:"resolved"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type VariantAttributeValue struct {
	VariantID        pgtype.UUID `json:"variant_id"`
	AttributeValueID pgtype.UUID `json:"attribute_value_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
}

type WsTicket struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
