// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oms.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommerceOrderMapping = `-- name: GetCommerceOrderMapping :one
SELECT id, org_id, tenant_id, connection_id, order_id, unified_order_id, external_order_id, last_synced_at, sync_direction, created_at FROM commerce_order_mappings
WHERE order_id = $1 AND tenant_id = $2 AND org_id = $3
`

type GetCommerceOrderMappingParams struct {
	OrderID  pgtype.UUID `json:"order_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetCommerceOrderMapping(ctx context.Context, arg GetCommerceOrderMappingParams) (CommerceOrderMapping, error) {
	row := q.db.QueryRow(ctx, getCommerceOrderMapping, arg.OrderID, arg.TenantID, arg.OrgID)
	var i CommerceOrderMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ConnectionID,
		&i.OrderID,
		&i.UnifiedOrderID,
		&i.ExternalOrderID,
		&i.LastSyncedAt,
		&i.SyncDirection,
		&i.CreatedAt,
	)
	return i, err
}

const getCommerceOrderMappingByExternal = `-- name: GetCommerceOrderMappingByExternal :one
SELECT id, org_id, tenant_id, connection_id, order_id, unified_order_id, external_order_id, last_synced_at, sync_direction, created_at FROM commerce_order_mappings
WHERE connection_id = $1 AND external_order_id = $2 AND tenant_id = $3 AND org_id = $4
`

type GetCommerceOrderMappingByExternalParams struct {
	ConnectionID    pgtype.UUID `json:"connection_id"`
	ExternalOrderID string      `json:"external_order_id"`
	TenantID        pgtype.UUID `json:"tenant_id"`
	OrgID           pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetCommerceOrderMappingByExternal(ctx context.Context, arg GetCommerceOrderMappingByExternalParams) (CommerceOrderMapping, error) {
	row := q.db.QueryRow(ctx, getCommerceOrderMappingByExternal,
		arg.ConnectionID,
		arg.ExternalOrderID,
		arg.TenantID,
		arg.OrgID,
	)
	var i CommerceOrderMapping
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ConnectionID,
		&i.OrderID,
		&i.UnifiedOrderID,
		&i.ExternalOrderID,
		&i.LastSyncedAt,
		&i.SyncDirection,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, org_id, tenant_id, customer_id, shipping_address_id, billing_address_id, status, currency, subtotal, discount_total, shipping_total, tax_total, total, payment_status, payment_provider, payment_reference, channel, source_platform, sales_channel_id, notes, tags, metadata, idempotency_key, confirmed_at, cancelled_at, fulfilled_at, created_at, updated_at, deleted_at FROM orders
WHERE id = $1 AND tenant_id = $2 AND org_id = $3
`

type GetOrderParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetOrder(ctx context.Context, arg GetOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, arg.ID, arg.TenantID, arg.OrgID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.CustomerID,
		&i.ShippingAddressID,
		&i.BillingAddressID,
		&i.Status,
		&i.Currency,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.ShippingTotal,
		&i.TaxTotal,
		&i.Total,
		&i.PaymentStatus,
		&i.PaymentProvider,
		&i.PaymentReference,
		&i.Channel,
		&i.SourcePlatform,
		&i.SalesChannelID,
		&i.Notes,
		&i.Tags,
		&i.Metadata,
		&i.IdempotencyKey,
		&i.ConfirmedAt,
		&i.CancelledAt,
		&i.FulfilledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, org_id, tenant_id, customer_id, shipping_address_id, billing_address_id, status, currency, subtotal, discount_total, shipping_total, tax_total, total, payment_status, payment_provider, payment_reference, channel, source_platform, sales_channel_id, notes, tags, metadata, idempotency_key, confirmed_at, cancelled_at, fulfilled_at, created_at, updated_at, deleted_at FROM orders
WHERE tenant_id = $1 AND org_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListOrdersParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders,
		arg.TenantID,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.CustomerID,
			&i.ShippingAddressID,
			&i.BillingAddressID,
			&i.Status,
			&i.Currency,
			&i.Subtotal,
			&i.DiscountTotal,
			&i.ShippingTotal,
			&i.TaxTotal,
			&i.Total,
			&i.PaymentStatus,
			&i.PaymentProvider,
			&i.PaymentReference,
			&i.Channel,
			&i.SourcePlatform,
			&i.SalesChannelID,
			&i.Notes,
			&i.Tags,
			&i.Metadata,
			&i.IdempotencyKey,
			&i.ConfirmedAt,
			&i.CancelledAt,
			&i.FulfilledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseInventoryForOrder = `-- name: ReleaseInventoryForOrder :exec
UPDATE inventory_levels
SET reserved_quantity = reserved_quantity - $1, updated_at = now()
WHERE variant_id = $2
  AND tenant_id = $3
  AND location_id = $4
  AND org_id = $5
`

type ReleaseInventoryForOrderParams struct {
	ReservedQuantity int32       `json:"reserved_quantity"`
	VariantID        pgtype.UUID `json:"variant_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	LocationID       pgtype.UUID `json:"location_id"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) ReleaseInventoryForOrder(ctx context.Context, arg ReleaseInventoryForOrderParams) error {
	_, err := q.db.Exec(ctx, releaseInventoryForOrder,
		arg.ReservedQuantity,
		arg.VariantID,
		arg.TenantID,
		arg.LocationID,
		arg.OrgID,
	)
	return err
}

const reserveInventoryForOrder = `-- name: ReserveInventoryForOrder :one
UPDATE inventory_levels
SET reserved_quantity = reserved_quantity + $1, updated_at = now()
WHERE variant_id = $2
  AND tenant_id = $3
  AND location_id = $4
  AND org_id = $5
  AND (available_quantity - reserved_quantity) >= $1
RETURNING id, org_id, tenant_id, variant_id, location_id, available_quantity, reserved_quantity, updated_by, created_at, updated_at
`

type ReserveInventoryForOrderParams struct {
	ReservedQuantity int32       `json:"reserved_quantity"`
	VariantID        pgtype.UUID `json:"variant_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	LocationID       pgtype.UUID `json:"location_id"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) ReserveInventoryForOrder(ctx context.Context, arg ReserveInventoryForOrderParams) (InventoryLevel, error) {
	row := q.db.QueryRow(ctx, reserveInventoryForOrder,
		arg.ReservedQuantity,
		arg.VariantID,
		arg.TenantID,
		arg.LocationID,
		arg.OrgID,
	)
	var i InventoryLevel
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.VariantID,
		&i.LocationID,
		&i.AvailableQuantity,
		&i.ReservedQuantity,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderPaymentStatus = `-- name: UpdateOrderPaymentStatus :exec
UPDATE orders
SET payment_status = $1, payment_provider = $2, payment_reference = $3, updated_at = now()
WHERE id = $4 AND tenant_id = $5 AND org_id = $6
`

type UpdateOrderPaymentStatusParams struct {
	PaymentStatus    pgtype.Text `json:"payment_status"`
	PaymentProvider  pgtype.Text `json:"payment_provider"`
	PaymentReference pgtype.Text `json:"payment_reference"`
	ID               pgtype.UUID `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	OrgID            pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderPaymentStatus,
		arg.PaymentStatus,
		arg.PaymentProvider,
		arg.PaymentReference,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1, updated_at = now()
WHERE id = $2 AND tenant_id = $3 AND org_id = $4
`

type UpdateOrderStatusParams struct {
	Status   OrderStatus `json:"status"`
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.Exec(ctx, updateOrderStatus,
		arg.Status,
		arg.ID,
		arg.TenantID,
		arg.OrgID,
	)
	return err
}
