// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTenantMember = `-- name: CreateTenantMember :one
INSERT INTO users (
  org_id,
  tenant_id,
  email,
  role
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, email, role, created_at
`

type CreateTenantMemberParams struct {
	OrgID    pgtype.UUID `json:"org_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Email    string      `json:"email"`
	Role     string      `json:"role"`
}

type CreateTenantMemberRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (CreateTenantMemberRow, error) {
	row := q.db.QueryRow(ctx, createTenantMember,
		arg.OrgID,
		arg.TenantID,
		arg.Email,
		arg.Role,
	)
	var i CreateTenantMemberRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantMembers = `-- name: ListTenantMembers :many
SELECT id, email, role, created_at
FROM users
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListTenantMembersRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListTenantMembers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantMembersRow, error) {
	rows, err := q.db.Query(ctx, listTenantMembers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTenantMembersRow
	for rows.Next() {
		var i ListTenantMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
