// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pim.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
    id, org_id, tenant_id, name, slug, type
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, org_id, tenant_id, name, slug, type, created_at, updated_at, deleted_at
`

type CreateAttributeParams struct {
	ID       pgtype.UUID `json:"id"`
	OrgID    pgtype.UUID `json:"org_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
	Type     pgtype.Text `json:"type"`
}

func (q *Queries) CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.Slug,
		arg.Type,
	)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.Slug,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAttributeGroup = `-- name: CreateAttributeGroup :one
INSERT INTO attribute_groups (
    org_id, tenant_id, name, description
) VALUES (
    $1, $2, $3, $4
) RETURNING id, org_id, tenant_id, name, description, created_at, updated_at
`

type CreateAttributeGroupParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateAttributeGroup(ctx context.Context, arg CreateAttributeGroupParams) (AttributeGroup, error) {
	row := q.db.QueryRow(ctx, createAttributeGroup,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.Description,
	)
	var i AttributeGroup
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttributeValue = `-- name: CreateAttributeValue :one
INSERT INTO attribute_values (
    id, org_id, tenant_id, attribute_id, value, slug
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, org_id, tenant_id, attribute_id, value, slug, created_at, updated_at
`

type CreateAttributeValueParams struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	AttributeID pgtype.UUID `json:"attribute_id"`
	Value       string      `json:"value"`
	Slug        string      `json:"slug"`
}

func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error) {
	row := q.db.QueryRow(ctx, createAttributeValue,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.AttributeID,
		arg.Value,
		arg.Slug,
	)
	var i AttributeValue
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.AttributeID,
		&i.Value,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBulkJob = `-- name: CreateBulkJob :one
INSERT INTO bulk_jobs (
    org_id, tenant_id, job_type, status, payload_json, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, org_id, tenant_id, job_type, status, payload_json, total_items, processed_items, created_by, created_at, updated_at
`

type CreateBulkJobParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	JobType     string      `json:"job_type"`
	Status      pgtype.Text `json:"status"`
	PayloadJson []byte      `json:"payload_json"`
	CreatedBy   pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (BulkJob, error) {
	row := q.db.QueryRow(ctx, createBulkJob,
		arg.OrgID,
		arg.TenantID,
		arg.JobType,
		arg.Status,
		arg.PayloadJson,
		arg.CreatedBy,
	)
	var i BulkJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.JobType,
		&i.Status,
		&i.PayloadJson,
		&i.TotalItems,
		&i.ProcessedItems,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventoryLedgerEntry = `-- name: CreateInventoryLedgerEntry :one
INSERT INTO inventory_ledger (
    org_id, tenant_id, variant_id, location_id, transaction_type, quantity_delta, unit_cost, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, tenant_id, variant_id, location_id, transaction_type, quantity_delta, reference_id, notes, created_by, created_at, unit_cost
`

type CreateInventoryLedgerEntryParams struct {
	OrgID           pgtype.UUID    `json:"org_id"`
	TenantID        pgtype.UUID    `json:"tenant_id"`
	VariantID       pgtype.UUID    `json:"variant_id"`
	LocationID      pgtype.UUID    `json:"location_id"`
	TransactionType interface{}    `json:"transaction_type"`
	QuantityDelta   int32          `json:"quantity_delta"`
	UnitCost        pgtype.Numeric `json:"unit_cost"`
	Notes           pgtype.Text    `json:"notes"`
	CreatedBy       pgtype.UUID    `json:"created_by"`
}

func (q *Queries) CreateInventoryLedgerEntry(ctx context.Context, arg CreateInventoryLedgerEntryParams) (InventoryLedger, error) {
	row := q.db.QueryRow(ctx, createInventoryLedgerEntry,
		arg.OrgID,
		arg.TenantID,
		arg.VariantID,
		arg.LocationID,
		arg.TransactionType,
		arg.QuantityDelta,
		arg.UnitCost,
		arg.Notes,
		arg.CreatedBy,
	)
	var i InventoryLedger
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.VariantID,
		&i.LocationID,
		&i.TransactionType,
		&i.QuantityDelta,
		&i.ReferenceID,
		&i.Notes,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UnitCost,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    id, org_id, tenant_id, title, description, status, product_type_id, created_by,
    short_description, long_description, category, brand, tags,
    launch_date, discontinue_date, warranty_period,
    is_taxable, is_returnable, requires_serial_number,
    seo_title, seo_description, seo_keywords, data_quality_score
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16,
    $17, $18, $19,
    $20, $21, $22, $23
) RETURNING id, org_id, tenant_id, title, description, status, product_type_id, created_by, updated_by, created_at, updated_at, deleted_at,
    short_description, long_description, category, brand, tags,
    launch_date, discontinue_date, warranty_period,
    is_taxable, is_returnable, requires_serial_number,
    seo_title, seo_description, seo_keywords, data_quality_score
`

type CreateProductParams struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Status               pgtype.Text        `json:"status"`
	ProductTypeID        pgtype.UUID        `json:"product_type_id"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	ShortDescription     pgtype.Text        `json:"short_description"`
	LongDescription      pgtype.Text        `json:"long_description"`
	Category             pgtype.Text        `json:"category"`
	Brand                pgtype.Text        `json:"brand"`
	Tags                 []byte             `json:"tags"`
	LaunchDate           pgtype.Timestamptz `json:"launch_date"`
	DiscontinueDate      pgtype.Timestamptz `json:"discontinue_date"`
	WarrantyPeriod       pgtype.Text        `json:"warranty_period"`
	IsTaxable            pgtype.Bool        `json:"is_taxable"`
	IsReturnable         pgtype.Bool        `json:"is_returnable"`
	RequiresSerialNumber pgtype.Bool        `json:"requires_serial_number"`
	SeoTitle             pgtype.Text        `json:"seo_title"`
	SeoDescription       pgtype.Text        `json:"seo_description"`
	SeoKeywords          []byte             `json:"seo_keywords"`
	DataQualityScore     pgtype.Int4        `json:"data_quality_score"`
}

type CreateProductRow struct {
	ID                   pgtype.UUID        `json:"id"`
	OrgID                pgtype.UUID        `json:"org_id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	Title                string             `json:"title"`
	Description          pgtype.Text        `json:"description"`
	Status               pgtype.Text        `json:"status"`
	ProductTypeID        pgtype.UUID        `json:"product_type_id"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
	UpdatedBy            pgtype.UUID        `json:"updated_by"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	ShortDescription     pgtype.Text        `json:"short_description"`
	LongDescription      pgtype.Text        `json:"long_description"`
	Category             pgtype.Text        `json:"category"`
	Brand                pgtype.Text        `json:"brand"`
	Tags                 []byte             `json:"tags"`
	LaunchDate           pgtype.Timestamptz `json:"launch_date"`
	DiscontinueDate      pgtype.Timestamptz `json:"discontinue_date"`
	WarrantyPeriod       pgtype.Text        `json:"warranty_period"`
	IsTaxable            pgtype.Bool        `json:"is_taxable"`
	IsReturnable         pgtype.Bool        `json:"is_returnable"`
	RequiresSerialNumber pgtype.Bool        `json:"requires_serial_number"`
	SeoTitle             pgtype.Text        `json:"seo_title"`
	SeoDescription       pgtype.Text        `json:"seo_description"`
	SeoKeywords          []byte             `json:"seo_keywords"`
	DataQualityScore     pgtype.Int4        `json:"data_quality_score"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.ProductTypeID,
		arg.CreatedBy,
		arg.ShortDescription,
		arg.LongDescription,
		arg.Category,
		arg.Brand,
		arg.Tags,
		arg.LaunchDate,
		arg.DiscontinueDate,
		arg.WarrantyPeriod,
		arg.IsTaxable,
		arg.IsReturnable,
		arg.RequiresSerialNumber,
		arg.SeoTitle,
		arg.SeoDescription,
		arg.SeoKeywords,
		arg.DataQualityScore,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.ProductTypeID,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Category,
		&i.Brand,
		&i.Tags,
		&i.LaunchDate,
		&i.DiscontinueDate,
		&i.WarrantyPeriod,
		&i.IsTaxable,
		&i.IsReturnable,
		&i.RequiresSerialNumber,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.DataQualityScore,
	)
	return i, err
}

const createProductMedia = `-- name: CreateProductMedia :one
INSERT INTO product_media (
    id, org_id, tenant_id, product_id, variant_id, url, alt_text, sort_order
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, org_id, tenant_id, product_id, variant_id, url, alt_text, sort_order, created_at, updated_at
`

type CreateProductMediaParams struct {
	ID        pgtype.UUID `json:"id"`
	OrgID     pgtype.UUID `json:"org_id"`
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
	Url       string      `json:"url"`
	AltText   pgtype.Text `json:"alt_text"`
	SortOrder pgtype.Int4 `json:"sort_order"`
}

func (q *Queries) CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductMedium, error) {
	row := q.db.QueryRow(ctx, createProductMedia,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.ProductID,
		arg.VariantID,
		arg.Url,
		arg.AltText,
		arg.SortOrder,
	)
	var i ProductMedium
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ProductID,
		&i.VariantID,
		&i.Url,
		&i.AltText,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductType = `-- name: CreateProductType :one
INSERT INTO product_types (
    id, org_id, tenant_id, name, description
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, org_id, tenant_id, name, description, created_at, updated_at, deleted_at
`

type CreateProductTypeParams struct {
	ID          pgtype.UUID `json:"id"`
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateProductType(ctx context.Context, arg CreateProductTypeParams) (ProductType, error) {
	row := q.db.QueryRow(ctx, createProductType,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.Description,
	)
	var i ProductType
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    id, org_id, tenant_id, product_id, sku, barcode, price, currency, created_by, data_quality_score
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, org_id, tenant_id, product_id, sku, barcode, price, currency, option_values, metadata, created_by, updated_by, created_at, updated_at, deleted_at, cost_price, data_quality_score
`

type CreateProductVariantParams struct {
	ID               pgtype.UUID    `json:"id"`
	OrgID            pgtype.UUID    `json:"org_id"`
	TenantID         pgtype.UUID    `json:"tenant_id"`
	ProductID        pgtype.UUID    `json:"product_id"`
	Sku              pgtype.Text    `json:"sku"`
	Barcode          pgtype.Text    `json:"barcode"`
	Price            pgtype.Numeric `json:"price"`
	Currency         pgtype.Text    `json:"currency"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
	DataQualityScore pgtype.Int4    `json:"data_quality_score"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ID,
		arg.OrgID,
		arg.TenantID,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Price,
		arg.Currency,
		arg.CreatedBy,
		arg.DataQualityScore,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Price,
		&i.Currency,
		&i.OptionValues,
		&i.Metadata,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CostPrice,
		&i.DataQualityScore,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET deleted_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type DeleteProductParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteProduct(ctx context.Context, arg DeleteProductParams) error {
	_, err := q.db.Exec(ctx, deleteProduct, arg.ID, arg.TenantID)
	return err
}

const fulfillReservation = `-- name: FulfillReservation :exec
UPDATE inventory_levels
SET 
    reserved_quantity = reserved_quantity - $3,
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = $1 AND variant_id = $2 AND location_id = $4
`

type FulfillReservationParams struct {
	TenantID         pgtype.UUID `json:"tenant_id"`
	VariantID        pgtype.UUID `json:"variant_id"`
	ReservedQuantity int32       `json:"reserved_quantity"`
	LocationID       pgtype.UUID `json:"location_id"`
}

func (q *Queries) FulfillReservation(ctx context.Context, arg FulfillReservationParams) error {
	_, err := q.db.Exec(ctx, fulfillReservation,
		arg.TenantID,
		arg.VariantID,
		arg.ReservedQuantity,
		arg.LocationID,
	)
	return err
}

const getAttributeGroups = `-- name: GetAttributeGroups :many
SELECT id, org_id, tenant_id, name, description, created_at, updated_at FROM attribute_groups 
WHERE tenant_id = $1 
ORDER BY created_at DESC
`

func (q *Queries) GetAttributeGroups(ctx context.Context, tenantID pgtype.UUID) ([]AttributeGroup, error) {
	rows, err := q.db.Query(ctx, getAttributeGroups, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeGroup
	for rows.Next() {
		var i AttributeGroup
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttributes = `-- name: GetAttributes :many
SELECT id, org_id, tenant_id, name, slug, type, created_at, updated_at, deleted_at FROM attributes 
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) GetAttributes(ctx context.Context, tenantID pgtype.UUID) ([]Attribute, error) {
	rows, err := q.db.Query(ctx, getAttributes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attribute
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Name,
			&i.Slug,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditEvents = `-- name: GetAuditEvents :many
SELECT id, org_id, tenant_id, actor_email, action, entity_type, entity_id, details, ip_address, created_at FROM audit_events 
WHERE tenant_id = $1 
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) GetAuditEvents(ctx context.Context, tenantID pgtype.UUID) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, getAuditEvents, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.ActorEmail,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Details,
			&i.IpAddress,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkJobs = `-- name: GetBulkJobs :many
SELECT id, org_id, tenant_id, job_type, status, payload_json, total_items, processed_items, created_by, created_at, updated_at FROM bulk_jobs 
WHERE tenant_id = $1 AND job_type = $2
ORDER BY created_at DESC
`

type GetBulkJobsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	JobType  string      `json:"job_type"`
}

func (q *Queries) GetBulkJobs(ctx context.Context, arg GetBulkJobsParams) ([]BulkJob, error) {
	rows, err := q.db.Query(ctx, getBulkJobs, arg.TenantID, arg.JobType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BulkJob
	for rows.Next() {
		var i BulkJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.JobType,
			&i.Status,
			&i.PayloadJson,
			&i.TotalItems,
			&i.ProcessedItems,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPIMStatsByTenant = `-- name: GetPIMStatsByTenant :one
SELECT 
    COUNT(DISTINCT p.id) as total_products,
    COALESCE(SUM(CASE WHEN il.available_quantity > 0 AND il.available_quantity < 20 THEN 1 ELSE 0 END), 0)::int as low_stock_variants,
    COALESCE(SUM(CASE WHEN il.available_quantity <= 0 THEN 1 ELSE 0 END), 0)::int as out_of_stock_variants,
    COALESCE(SUM(il.available_quantity * pv.cost_price), 0)::numeric as total_inventory_value
FROM products p
LEFT JOIN product_variants pv ON pv.product_id = p.id AND pv.deleted_at IS NULL
LEFT JOIN inventory_levels il ON il.variant_id = pv.id
WHERE p.tenant_id = $1 AND p.deleted_at IS NULL
`

type GetPIMStatsByTenantRow struct {
	TotalProducts       int64          `json:"total_products"`
	LowStockVariants    int32          `json:"low_stock_variants"`
	OutOfStockVariants  int32          `json:"out_of_stock_variants"`
	TotalInventoryValue pgtype.Numeric `json:"total_inventory_value"`
}

func (q *Queries) GetPIMStatsByTenant(ctx context.Context, tenantID pgtype.UUID) (GetPIMStatsByTenantRow, error) {
	row := q.db.QueryRow(ctx, getPIMStatsByTenant, tenantID)
	var i GetPIMStatsByTenantRow
	err := row.Scan(
		&i.TotalProducts,
		&i.LowStockVariants,
		&i.OutOfStockVariants,
		&i.TotalInventoryValue,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, org_id, tenant_id, title, description, status, options, metadata, embedding, created_by, updated_by, created_at, updated_at, deleted_at, product_type_id, short_description, long_description, category, brand, tags, launch_date, discontinue_date, warranty_period, is_taxable, is_returnable, requires_serial_number, seo_title, seo_description, seo_keywords, data_quality_score, category_id, brand_id
FROM products
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
`

type GetProductParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetProduct(ctx context.Context, arg GetProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, arg.ID, arg.TenantID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Options,
		&i.Metadata,
		&i.Embedding,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductTypeID,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Category,
		&i.Brand,
		&i.Tags,
		&i.LaunchDate,
		&i.DiscontinueDate,
		&i.WarrantyPeriod,
		&i.IsTaxable,
		&i.IsReturnable,
		&i.RequiresSerialNumber,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.DataQualityScore,
		&i.CategoryID,
		&i.BrandID,
	)
	return i, err
}

const getProductMedia = `-- name: GetProductMedia :many
SELECT id, org_id, tenant_id, product_id, variant_id, url, alt_text, sort_order, created_at, updated_at FROM product_media 
WHERE tenant_id = $1 AND (product_id = $2 OR variant_id = $3)
ORDER BY sort_order ASC
`

type GetProductMediaParams struct {
	TenantID  pgtype.UUID `json:"tenant_id"`
	ProductID pgtype.UUID `json:"product_id"`
	VariantID pgtype.UUID `json:"variant_id"`
}

func (q *Queries) GetProductMedia(ctx context.Context, arg GetProductMediaParams) ([]ProductMedium, error) {
	rows, err := q.db.Query(ctx, getProductMedia, arg.TenantID, arg.ProductID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductMedium
	for rows.Next() {
		var i ProductMedium
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.ProductID,
			&i.VariantID,
			&i.Url,
			&i.AltText,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductTypes = `-- name: GetProductTypes :many
SELECT id, org_id, tenant_id, name, description, created_at, updated_at, deleted_at FROM product_types 
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) GetProductTypes(ctx context.Context, tenantID pgtype.UUID) ([]ProductType, error) {
	rows, err := q.db.Query(ctx, getProductTypes, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductType
	for rows.Next() {
		var i ProductType
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductWithVariants = `-- name: GetProductWithVariants :many
SELECT 
    p.id as product_id,
    p.title as product_title,
    p.data_quality_score as product_score,
    v.id as variant_id,
    v.sku,
    v.price,
    av.value as attribute_value,
    a.name as attribute_name
FROM products p
LEFT JOIN product_variants v ON v.product_id = p.id
LEFT JOIN variant_attribute_values vav ON vav.variant_id = v.id
LEFT JOIN attribute_values av ON av.id = vav.attribute_value_id
LEFT JOIN attributes a ON a.id = av.attribute_id
WHERE p.id = $1 AND p.tenant_id = current_setting('app.current_tenant', true)::uuid
  AND p.deleted_at IS NULL AND v.deleted_at IS NULL
`

type GetProductWithVariantsRow struct {
	ProductID      pgtype.UUID    `json:"product_id"`
	ProductTitle   string         `json:"product_title"`
	ProductScore   pgtype.Int4    `json:"product_score"`
	VariantID      pgtype.UUID    `json:"variant_id"`
	Sku            pgtype.Text    `json:"sku"`
	Price          pgtype.Numeric `json:"price"`
	AttributeValue pgtype.Text    `json:"attribute_value"`
	AttributeName  pgtype.Text    `json:"attribute_name"`
}

func (q *Queries) GetProductWithVariants(ctx context.Context, id pgtype.UUID) ([]GetProductWithVariantsRow, error) {
	rows, err := q.db.Query(ctx, getProductWithVariants, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductWithVariantsRow
	for rows.Next() {
		var i GetProductWithVariantsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductTitle,
			&i.ProductScore,
			&i.VariantID,
			&i.Sku,
			&i.Price,
			&i.AttributeValue,
			&i.AttributeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopLowStockProducts = `-- name: GetTopLowStockProducts :many
SELECT 
    p.id as product_id,
    p.title as product_title,
    il.available_quantity as stock_left
FROM products p
JOIN product_variants pv ON pv.product_id = p.id
JOIN inventory_levels il ON il.variant_id = pv.id
WHERE p.tenant_id = $1 
  AND p.deleted_at IS NULL
  AND pv.deleted_at IS NULL
  AND il.available_quantity < 20
ORDER BY il.available_quantity ASC
LIMIT 5
`

type GetTopLowStockProductsRow struct {
	ProductID    pgtype.UUID `json:"product_id"`
	ProductTitle string      `json:"product_title"`
	StockLeft    int32       `json:"stock_left"`
}

func (q *Queries) GetTopLowStockProducts(ctx context.Context, tenantID pgtype.UUID) ([]GetTopLowStockProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopLowStockProducts, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopLowStockProductsRow
	for rows.Next() {
		var i GetTopLowStockProductsRow
		if err := rows.Scan(&i.ProductID, &i.ProductTitle, &i.StockLeft); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getValidationIssues = `-- name: GetValidationIssues :many
SELECT id, org_id, tenant_id, product_id, issue_type, severity, message, resolved, created_at, updated_at FROM validation_issues 
WHERE tenant_id = $1 AND resolved = false
ORDER BY created_at DESC
`

func (q *Queries) GetValidationIssues(ctx context.Context, tenantID pgtype.UUID) ([]ValidationIssue, error) {
	rows, err := q.db.Query(ctx, getValidationIssues, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValidationIssue
	for rows.Next() {
		var i ValidationIssue
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.ProductID,
			&i.IssueType,
			&i.Severity,
			&i.Message,
			&i.Resolved,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkProductTypeAttribute = `-- name: LinkProductTypeAttribute :exec
INSERT INTO product_type_attributes (
    product_type_id, attribute_id, org_id, tenant_id
) VALUES (
    $1, $2, $3, $4
)
`

type LinkProductTypeAttributeParams struct {
	ProductTypeID pgtype.UUID `json:"product_type_id"`
	AttributeID   pgtype.UUID `json:"attribute_id"`
	OrgID         pgtype.UUID `json:"org_id"`
	TenantID      pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) LinkProductTypeAttribute(ctx context.Context, arg LinkProductTypeAttributeParams) error {
	_, err := q.db.Exec(ctx, linkProductTypeAttribute,
		arg.ProductTypeID,
		arg.AttributeID,
		arg.OrgID,
		arg.TenantID,
	)
	return err
}

const linkVariantAttributeValue = `-- name: LinkVariantAttributeValue :exec
INSERT INTO variant_attribute_values (
    variant_id, attribute_value_id, org_id, tenant_id
) VALUES (
    $1, $2, $3, $4
)
`

type LinkVariantAttributeValueParams struct {
	VariantID        pgtype.UUID `json:"variant_id"`
	AttributeValueID pgtype.UUID `json:"attribute_value_id"`
	OrgID            pgtype.UUID `json:"org_id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) LinkVariantAttributeValue(ctx context.Context, arg LinkVariantAttributeValueParams) error {
	_, err := q.db.Exec(ctx, linkVariantAttributeValue,
		arg.VariantID,
		arg.AttributeValueID,
		arg.OrgID,
		arg.TenantID,
	)
	return err
}

const listProductsByTenant = `-- name: ListProductsByTenant :many
SELECT 
    p.id, 
    p.title, 
    p.category, 
    p.status, 
    p.updated_at
FROM products p
WHERE p.tenant_id = $1 AND p.deleted_at IS NULL
ORDER BY p.updated_at DESC
LIMIT 100
`

type ListProductsByTenantRow struct {
	ID        pgtype.UUID        `json:"id"`
	Title     string             `json:"title"`
	Category  pgtype.Text        `json:"category"`
	Status    pgtype.Text        `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListProductsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsByTenantRow, error) {
	rows, err := q.db.Query(ctx, listProductsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByTenantRow
	for rows.Next() {
		var i ListProductsByTenantRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Category,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForUCP = `-- name: ListProductsForUCP :many
SELECT 
    p.id as product_id,
    p.title,
    p.description,
    p.brand,
    p.category,
    pv.id as variant_id,
    pv.sku,
    pv.barcode as gtin,
    pv.price,
    pv.currency,
    pm.url as image_url
FROM products p
LEFT JOIN product_variants pv ON p.id = pv.product_id
LEFT JOIN product_media pm ON p.id = pm.product_id
WHERE p.tenant_id = $1 AND p.status = 'ACTIVE' AND p.deleted_at IS NULL AND pv.deleted_at IS NULL
`

type ListProductsForUCPRow struct {
	ProductID   pgtype.UUID    `json:"product_id"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	Brand       pgtype.Text    `json:"brand"`
	Category    pgtype.Text    `json:"category"`
	VariantID   pgtype.UUID    `json:"variant_id"`
	Sku         pgtype.Text    `json:"sku"`
	Gtin        pgtype.Text    `json:"gtin"`
	Price       pgtype.Numeric `json:"price"`
	Currency    pgtype.Text    `json:"currency"`
	ImageUrl    pgtype.Text    `json:"image_url"`
}

func (q *Queries) ListProductsForUCP(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsForUCPRow, error) {
	rows, err := q.db.Query(ctx, listProductsForUCP, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsForUCPRow
	for rows.Next() {
		var i ListProductsForUCPRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Title,
			&i.Description,
			&i.Brand,
			&i.Category,
			&i.VariantID,
			&i.Sku,
			&i.Gtin,
			&i.Price,
			&i.Currency,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reserveInventory = `-- name: ReserveInventory :exec
UPDATE inventory_levels
SET 
    available_quantity = available_quantity - $3,
    reserved_quantity = reserved_quantity + $3,
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_id = $1 AND variant_id = $2 AND location_id = $4
`

type ReserveInventoryParams struct {
	TenantID          pgtype.UUID `json:"tenant_id"`
	VariantID         pgtype.UUID `json:"variant_id"`
	AvailableQuantity int32       `json:"available_quantity"`
	LocationID        pgtype.UUID `json:"location_id"`
}

func (q *Queries) ReserveInventory(ctx context.Context, arg ReserveInventoryParams) error {
	_, err := q.db.Exec(ctx, reserveInventory,
		arg.TenantID,
		arg.VariantID,
		arg.AvailableQuantity,
		arg.LocationID,
	)
	return err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    title = COALESCE(NULLIF($3::text, ''), title),
    description = COALESCE(NULLIF($4::text, ''), description),
    category = COALESCE(NULLIF($5::text, ''), category),
    updated_at = NOW()
WHERE id = $1 AND tenant_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, tenant_id, title, description, status, options, metadata, embedding, created_by, updated_by, created_at, updated_at, deleted_at, product_type_id, short_description, long_description, category, brand, tags, launch_date, discontinue_date, warranty_period, is_taxable, is_returnable, requires_serial_number, seo_title, seo_description, seo_keywords, data_quality_score, category_id, brand_id
`

type UpdateProductParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Column3  string      `json:"column_3"`
	Column4  string      `json:"column_4"`
	Column5  string      `json:"column_5"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.TenantID,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Options,
		&i.Metadata,
		&i.Embedding,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ProductTypeID,
		&i.ShortDescription,
		&i.LongDescription,
		&i.Category,
		&i.Brand,
		&i.Tags,
		&i.LaunchDate,
		&i.DiscontinueDate,
		&i.WarrantyPeriod,
		&i.IsTaxable,
		&i.IsReturnable,
		&i.RequiresSerialNumber,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.SeoKeywords,
		&i.DataQualityScore,
		&i.CategoryID,
		&i.BrandID,
	)
	return i, err
}
