// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pim_taxonomy.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBrand = `-- name: CreateBrand :one
INSERT INTO brands (org_id, tenant_id, name, description, logo_url)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, org_id, tenant_id, name, description, logo_url, created_at, updated_at, deleted_at
`

type CreateBrandParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logo_url"`
}

func (q *Queries) CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error) {
	row := q.db.QueryRow(ctx, createBrand,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
	)
	var i Brand
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (org_id, tenant_id, parent_id, name, slug, description)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, tenant_id, parent_id, name, slug, description, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	OrgID       pgtype.UUID `json:"org_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	ParentID    pgtype.UUID `json:"parent_id"`
	Name        string      `json:"name"`
	Slug        string      `json:"slug"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.OrgID,
		arg.TenantID,
		arg.ParentID,
		arg.Name,
		arg.Slug,
		arg.Description,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.ParentID,
		&i.Name,
		&i.Slug,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBrands = `-- name: GetBrands :many
SELECT id, org_id, tenant_id, name, description, logo_url, created_at, updated_at, deleted_at FROM brands 
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) GetBrands(ctx context.Context, tenantID pgtype.UUID) ([]Brand, error) {
	rows, err := q.db.Query(ctx, getBrands, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Brand
	for rows.Next() {
		var i Brand
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategories = `-- name: GetCategories :many
SELECT id, org_id, tenant_id, parent_id, name, slug, description, created_at, updated_at, deleted_at FROM categories 
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) GetCategories(ctx context.Context, tenantID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
