// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: procurement.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (
    org_id, tenant_id, supplier_id, status, total_amount, currency, expected_delivery_date, notes, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, org_id, tenant_id, supplier_id, status, total_amount, currency, expected_delivery_date, notes, created_by, approved_by, created_at, updated_at, deleted_at
`

type CreatePurchaseOrderParams struct {
	OrgID                pgtype.UUID        `json:"org_id"`
	TenantID             pgtype.UUID        `json:"tenant_id"`
	SupplierID           pgtype.UUID        `json:"supplier_id"`
	Status               NullPoStatus       `json:"status"`
	TotalAmount          pgtype.Numeric     `json:"total_amount"`
	Currency             pgtype.Text        `json:"currency"`
	ExpectedDeliveryDate pgtype.Timestamptz `json:"expected_delivery_date"`
	Notes                pgtype.Text        `json:"notes"`
	CreatedBy            pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.OrgID,
		arg.TenantID,
		arg.SupplierID,
		arg.Status,
		arg.TotalAmount,
		arg.Currency,
		arg.ExpectedDeliveryDate,
		arg.Notes,
		arg.CreatedBy,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.SupplierID,
		&i.Status,
		&i.TotalAmount,
		&i.Currency,
		&i.ExpectedDeliveryDate,
		&i.Notes,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPurchaseOrderLineItem = `-- name: CreatePurchaseOrderLineItem :one
INSERT INTO purchase_order_line_items (
    org_id, tenant_id, po_id, variant_id, quantity, unit_price, subtotal
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, org_id, tenant_id, po_id, variant_id, quantity, unit_price, subtotal, received_quantity, created_at
`

type CreatePurchaseOrderLineItemParams struct {
	OrgID     pgtype.UUID    `json:"org_id"`
	TenantID  pgtype.UUID    `json:"tenant_id"`
	PoID      pgtype.UUID    `json:"po_id"`
	VariantID pgtype.UUID    `json:"variant_id"`
	Quantity  int32          `json:"quantity"`
	UnitPrice pgtype.Numeric `json:"unit_price"`
	Subtotal  pgtype.Numeric `json:"subtotal"`
}

func (q *Queries) CreatePurchaseOrderLineItem(ctx context.Context, arg CreatePurchaseOrderLineItemParams) (PurchaseOrderLineItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderLineItem,
		arg.OrgID,
		arg.TenantID,
		arg.PoID,
		arg.VariantID,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
	)
	var i PurchaseOrderLineItem
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.PoID,
		&i.VariantID,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.ReceivedQuantity,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
    org_id, tenant_id, name, contact_email, payment_terms, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, org_id, tenant_id, name, contact_email, payment_terms, metadata, created_at, updated_at, deleted_at
`

type CreateSupplierParams struct {
	OrgID        pgtype.UUID `json:"org_id"`
	TenantID     pgtype.UUID `json:"tenant_id"`
	Name         string      `json:"name"`
	ContactEmail pgtype.Text `json:"contact_email"`
	PaymentTerms pgtype.Text `json:"payment_terms"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.OrgID,
		arg.TenantID,
		arg.Name,
		arg.ContactEmail,
		arg.PaymentTerms,
		arg.Metadata,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.PaymentTerms,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFirstSupplier = `-- name: GetFirstSupplier :one
SELECT id, org_id, tenant_id, name, contact_email, payment_terms, metadata, created_at, updated_at, deleted_at FROM suppliers 
WHERE tenant_id = $1 LIMIT 1
`

func (q *Queries) GetFirstSupplier(ctx context.Context, tenantID pgtype.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getFirstSupplier, tenantID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.PaymentTerms,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, org_id, tenant_id, name, contact_email, payment_terms, metadata, created_at, updated_at, deleted_at FROM suppliers 
WHERE id = $1 AND tenant_id = $2
`

type GetSupplierParams struct {
	ID       pgtype.UUID `json:"id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.ID, arg.TenantID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.Name,
		&i.ContactEmail,
		&i.PaymentTerms,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
