// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CleanupWSTickets(ctx context.Context) error
	ConsumeWSTicket(ctx context.Context, id pgtype.UUID) (ConsumeWSTicketRow, error)
	CreateAttribute(ctx context.Context, arg CreateAttributeParams) (Attribute, error)
	CreateAttributeGroup(ctx context.Context, arg CreateAttributeGroupParams) (AttributeGroup, error)
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateBulkJob(ctx context.Context, arg CreateBulkJobParams) (BulkJob, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCommerceConnection(ctx context.Context, arg CreateCommerceConnectionParams) (CommerceConnection, error)
	CreateInventoryLedgerEntry(ctx context.Context, arg CreateInventoryLedgerEntryParams) (InventoryLedger, error)
	CreateOrUpdateProductChannelListing(ctx context.Context, arg CreateOrUpdateProductChannelListingParams) (ProductChannelListing, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateProductMedia(ctx context.Context, arg CreateProductMediaParams) (ProductMedium, error)
	CreateProductType(ctx context.Context, arg CreateProductTypeParams) (ProductType, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseOrderLineItem(ctx context.Context, arg CreatePurchaseOrderLineItemParams) (PurchaseOrderLineItem, error)
	CreateSalesChannel(ctx context.Context, arg CreateSalesChannelParams) (SalesChannel, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTenantIntegration(ctx context.Context, arg CreateTenantIntegrationParams) (TenantIntegration, error)
	CreateTenantMember(ctx context.Context, arg CreateTenantMemberParams) (CreateTenantMemberRow, error)
	CreateWSTicket(ctx context.Context, arg CreateWSTicketParams) (pgtype.UUID, error)
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	FulfillReservation(ctx context.Context, arg FulfillReservationParams) error
	GetAttributeGroups(ctx context.Context, tenantID pgtype.UUID) ([]AttributeGroup, error)
	GetAttributes(ctx context.Context, tenantID pgtype.UUID) ([]Attribute, error)
	GetAuditEvents(ctx context.Context, tenantID pgtype.UUID) ([]AuditEvent, error)
	GetAuditEventsByTenant(ctx context.Context, arg GetAuditEventsByTenantParams) ([]GetAuditEventsByTenantRow, error)
	GetBrands(ctx context.Context, tenantID pgtype.UUID) ([]Brand, error)
	GetBulkJobs(ctx context.Context, arg GetBulkJobsParams) ([]BulkJob, error)
	GetCategories(ctx context.Context, tenantID pgtype.UUID) ([]Category, error)
	GetCommerceConnections(ctx context.Context, arg GetCommerceConnectionsParams) ([]CommerceConnection, error)
	GetCommerceOrderMapping(ctx context.Context, arg GetCommerceOrderMappingParams) (CommerceOrderMapping, error)
	GetCommerceOrderMappingByExternal(ctx context.Context, arg GetCommerceOrderMappingByExternalParams) (CommerceOrderMapping, error)
	GetFirstSupplier(ctx context.Context, tenantID pgtype.UUID) (Supplier, error)
	GetOrder(ctx context.Context, arg GetOrderParams) (Order, error)
	GetPIMStatsByTenant(ctx context.Context, tenantID pgtype.UUID) (GetPIMStatsByTenantRow, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductMedia(ctx context.Context, arg GetProductMediaParams) ([]ProductMedium, error)
	GetProductTypes(ctx context.Context, tenantID pgtype.UUID) ([]ProductType, error)
	GetProductWithChannelOverrides(ctx context.Context, arg GetProductWithChannelOverridesParams) (GetProductWithChannelOverridesRow, error)
	GetProductWithVariants(ctx context.Context, id pgtype.UUID) ([]GetProductWithVariantsRow, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	GetTenantByConnectionID(ctx context.Context, unifiedConnectionID string) (GetTenantByConnectionIDRow, error)
	GetTenantIntegrationByCategory(ctx context.Context, arg GetTenantIntegrationByCategoryParams) (string, error)
	GetTenantSettings(ctx context.Context, arg GetTenantSettingsParams) (TenantSetting, error)
	GetTopLowStockProducts(ctx context.Context, tenantID pgtype.UUID) ([]GetTopLowStockProductsRow, error)
	GetValidationIssues(ctx context.Context, tenantID pgtype.UUID) ([]ValidationIssue, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (pgtype.UUID, error)
	LinkProductTypeAttribute(ctx context.Context, arg LinkProductTypeAttributeParams) error
	LinkVariantAttributeValue(ctx context.Context, arg LinkVariantAttributeValueParams) error
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error)
	ListProductsByTenant(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsByTenantRow, error)
	ListProductsForUCP(ctx context.Context, tenantID pgtype.UUID) ([]ListProductsForUCPRow, error)
	ListSalesChannels(ctx context.Context, arg ListSalesChannelsParams) ([]SalesChannel, error)
	ListTenantMembers(ctx context.Context, tenantID pgtype.UUID) ([]ListTenantMembersRow, error)
	ReleaseInventoryForOrder(ctx context.Context, arg ReleaseInventoryForOrderParams) error
	ReserveInventory(ctx context.Context, arg ReserveInventoryParams) error
	ReserveInventoryForOrder(ctx context.Context, arg ReserveInventoryForOrderParams) (InventoryLevel, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) error
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error)
}

var _ Querier = (*Queries)(nil)
