// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantSettings = `-- name: GetTenantSettings :one
SELECT id, org_id, tenant_id, inventory_allocation_model, auto_po_enabled, default_low_stock_threshold, costing_method, updated_by, created_at, updated_at FROM tenant_settings 
WHERE tenant_id = $1 AND org_id = $2 LIMIT 1
`

type GetTenantSettingsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetTenantSettings(ctx context.Context, arg GetTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, getTenantSettings, arg.TenantID, arg.OrgID)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.InventoryAllocationModel,
		&i.AutoPoEnabled,
		&i.DefaultLowStockThreshold,
		&i.CostingMethod,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertTenantSettings = `-- name: UpsertTenantSettings :one
INSERT INTO tenant_settings (
    org_id, tenant_id, inventory_allocation_model, auto_po_enabled, default_low_stock_threshold, costing_method, updated_by, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, CURRENT_TIMESTAMP
) ON CONFLICT (tenant_id) DO UPDATE
SET 
    inventory_allocation_model = EXCLUDED.inventory_allocation_model,
    auto_po_enabled = EXCLUDED.auto_po_enabled,
    default_low_stock_threshold = EXCLUDED.default_low_stock_threshold,
    costing_method = EXCLUDED.costing_method,
    updated_by = EXCLUDED.updated_by,
    updated_at = CURRENT_TIMESTAMP
WHERE tenant_settings.org_id = EXCLUDED.org_id
RETURNING id, org_id, tenant_id, inventory_allocation_model, auto_po_enabled, default_low_stock_threshold, costing_method, updated_by, created_at, updated_at
`

type UpsertTenantSettingsParams struct {
	OrgID                    pgtype.UUID `json:"org_id"`
	TenantID                 pgtype.UUID `json:"tenant_id"`
	InventoryAllocationModel pgtype.Text `json:"inventory_allocation_model"`
	AutoPoEnabled            pgtype.Bool `json:"auto_po_enabled"`
	DefaultLowStockThreshold pgtype.Int4 `json:"default_low_stock_threshold"`
	CostingMethod            pgtype.Text `json:"costing_method"`
	UpdatedBy                pgtype.UUID `json:"updated_by"`
}

func (q *Queries) UpsertTenantSettings(ctx context.Context, arg UpsertTenantSettingsParams) (TenantSetting, error) {
	row := q.db.QueryRow(ctx, upsertTenantSettings,
		arg.OrgID,
		arg.TenantID,
		arg.InventoryAllocationModel,
		arg.AutoPoEnabled,
		arg.DefaultLowStockThreshold,
		arg.CostingMethod,
		arg.UpdatedBy,
	)
	var i TenantSetting
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.InventoryAllocationModel,
		&i.AutoPoEnabled,
		&i.DefaultLowStockThreshold,
		&i.CostingMethod,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
