// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupWSTickets = `-- name: CleanupWSTickets :exec
DELETE FROM ws_tickets
WHERE expires_at <= NOW()
`

func (q *Queries) CleanupWSTickets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupWSTickets)
	return err
}

const consumeWSTicket = `-- name: ConsumeWSTicket :one
DELETE FROM ws_tickets
WHERE id = $1 AND expires_at > NOW()
RETURNING tenant_id, org_id, user_id, role
`

type ConsumeWSTicketRow struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
	UserID   string      `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) ConsumeWSTicket(ctx context.Context, id pgtype.UUID) (ConsumeWSTicketRow, error) {
	row := q.db.QueryRow(ctx, consumeWSTicket, id)
	var i ConsumeWSTicketRow
	err := row.Scan(
		&i.TenantID,
		&i.OrgID,
		&i.UserID,
		&i.Role,
	)
	return i, err
}

const createWSTicket = `-- name: CreateWSTicket :one
INSERT INTO ws_tickets (
    tenant_id,
    org_id,
    user_id,
    role,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id
`

type CreateWSTicketParams struct {
	TenantID  pgtype.UUID        `json:"tenant_id"`
	OrgID     pgtype.UUID        `json:"org_id"`
	UserID    string             `json:"user_id"`
	Role      string             `json:"role"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateWSTicket(ctx context.Context, arg CreateWSTicketParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createWSTicket,
		arg.TenantID,
		arg.OrgID,
		arg.UserID,
		arg.Role,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
