// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: unified.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCommerceConnection = `-- name: CreateCommerceConnection :one
INSERT INTO commerce_connections (
  org_id, tenant_id, unified_connection_id, provider
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, org_id, tenant_id, unified_connection_id, provider, status, metadata, created_at, updated_at, deleted_at
`

type CreateCommerceConnectionParams struct {
	OrgID               pgtype.UUID `json:"org_id"`
	TenantID            pgtype.UUID `json:"tenant_id"`
	UnifiedConnectionID string      `json:"unified_connection_id"`
	Provider            string      `json:"provider"`
}

func (q *Queries) CreateCommerceConnection(ctx context.Context, arg CreateCommerceConnectionParams) (CommerceConnection, error) {
	row := q.db.QueryRow(ctx, createCommerceConnection,
		arg.OrgID,
		arg.TenantID,
		arg.UnifiedConnectionID,
		arg.Provider,
	)
	var i CommerceConnection
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.TenantID,
		&i.UnifiedConnectionID,
		&i.Provider,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommerceConnections = `-- name: GetCommerceConnections :many
SELECT id, org_id, tenant_id, unified_connection_id, provider, status, metadata, created_at, updated_at, deleted_at FROM commerce_connections
WHERE tenant_id = $1 AND org_id = $2 AND status = 'ACTIVE' AND deleted_at IS NULL
`

type GetCommerceConnectionsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	OrgID    pgtype.UUID `json:"org_id"`
}

func (q *Queries) GetCommerceConnections(ctx context.Context, arg GetCommerceConnectionsParams) ([]CommerceConnection, error) {
	rows, err := q.db.Query(ctx, getCommerceConnections, arg.TenantID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommerceConnection
	for rows.Next() {
		var i CommerceConnection
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.TenantID,
			&i.UnifiedConnectionID,
			&i.Provider,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTenantByConnectionID = `-- name: GetTenantByConnectionID :one
SELECT org_id, tenant_id FROM commerce_connections
WHERE unified_connection_id = $1 AND status = 'ACTIVE' AND deleted_at IS NULL
LIMIT 1
`

type GetTenantByConnectionIDRow struct {
	OrgID    pgtype.UUID `json:"org_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) GetTenantByConnectionID(ctx context.Context, unifiedConnectionID string) (GetTenantByConnectionIDRow, error) {
	row := q.db.QueryRow(ctx, getTenantByConnectionID, unifiedConnectionID)
	var i GetTenantByConnectionIDRow
	err := row.Scan(&i.OrgID, &i.TenantID)
	return i, err
}
