steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--tag=gcr.io/$PROJECT_ID/ops-api:latest',
      '--file=services/ops-api/Dockerfile',
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/ops-api:latest'
